import type { Metadata } from "next";
import { LegalDocShell } from "@/app/legal/LegalDocShell";
import { legalOperatorName, legalPublicContactEmail } from "@/lib/legalEntity";
import { publicSiteOrigin } from "@/lib/publicSiteUrl";

export const metadata: Metadata = {
  title: "Privacy Policy",
  robots: { index: true, follow: true },
};

const UPDATED = "May 13, 2026";

export default function PrivacyPage() {
  const operator = legalOperatorName();
  const contact = legalPublicContactEmail();
  let host = "our platform";
  try {
    host = publicSiteOrigin().host;
  } catch {
    /* build without metadataBase */
  }

  return (
    <LegalDocShell title="Privacy Policy" updated={UPDATED}>
      <section className="space-y-3">
        <h2>1. Introduction</h2>
        <p>
          This Privacy Policy describes how <strong>{operator}</strong> (&quot;we,&quot; &quot;us,&quot; or
          &quot;our&quot;) collects, uses, stores, and shares information when you use our website and services
          (the &quot;Service&quot;), including the platform available at <strong>{host}</strong>.
        </p>
        <p>
          By using the Service, you agree to the collection and use of information as described in this Policy.
          If you do not agree, please discontinue use of the Service.
        </p>
      </section>

      <section className="space-y-3">
        <h2>2. Information We Collect</h2>
        <p>We collect information you provide directly, data generated by your use of the Service, and limited data from third-party services you authorize.</p>

        <p><strong>Account information</strong></p>
        <ul>
          <li>Email address and display name (required to create an account).</li>
          <li>Password (stored as a one-way bcrypt hash — we cannot recover your plaintext password).</li>
          <li>Profile photo, if you choose to upload one.</li>
          <li>Passkey / WebAuthn credential data, if you register a biometric or hardware key.</li>
        </ul>

        <p><strong>Amazon seller account data</strong> (only if you connect your Amazon account)</p>
        <ul>
          <li>
            Amazon Seller ID and store name, retrieved via the Amazon Selling Partner API (&quot;SP-API&quot;)
            after you authorize the connection.
          </li>
          <li>
            An SP-API OAuth refresh token, stored in AES-GCM encrypted form. This token allows the Service to
            query Amazon&apos;s APIs on your behalf. It is never transmitted to third parties and is deleted
            when you disconnect your Amazon account.
          </li>
          <li>
            Product, pricing, fee, and restriction data retrieved from Amazon APIs in response to your in-app
            requests. This data is processed in real time and may be cached briefly to reduce API load.
          </li>
        </ul>

        <p><strong>Usage and activity data</strong></p>
        <ul>
          <li>
            Records of features you use (product analyses, catalog searches, keyword searches, offer lookups)
            aggregated as monthly usage counts. This data is used to enforce plan quotas and to improve the
            Service.
          </li>
          <li>
            Wholesale prices and product identifiers (ASINs, UPCs) that you submit for analysis. This data is
            processed to return results and is not retained beyond the session cache.
          </li>
        </ul>

        <p><strong>Payment and billing data</strong></p>
        <ul>
          <li>
            Stripe customer ID and subscription status. All payment card details are collected and stored
            directly by Stripe, Inc. — we never see or store your card number, CVV, or full billing address.
          </li>
          <li>Subscription plan tier, billing period, and trial end date.</li>
          <li>Records of promo code redemptions.</li>
        </ul>

        <p><strong>Technical and log data</strong></p>
        <ul>
          <li>Server logs may include IP addresses, request timestamps, HTTP method and path, and error details. These are retained for security and debugging purposes.</li>
          <li>Browser-side data stored in <code>localStorage</code> (saved product lists, appearance preferences) remains on your device and is not transmitted to our servers.</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2>3. How We Use Your Information</h2>
        <ul>
          <li><strong>Provide the Service:</strong> authenticate your account, process your requests, return product analysis results, and display your preferences.</li>
          <li><strong>Billing and subscriptions:</strong> create and manage your Stripe subscription, enforce usage quotas, and process payments.</li>
          <li><strong>Security and abuse prevention:</strong> detect and prevent fraud, unauthorized access, and violations of these Terms.</li>
          <li><strong>Service communications:</strong> send transactional emails (password resets, account notices). We do not send marketing emails without your opt-in consent.</li>
          <li><strong>Rate limiting:</strong> enforce per-user and per-endpoint request limits to protect service stability.</li>
          <li><strong>Service improvement:</strong> analyze aggregate, anonymized usage patterns to improve features and performance.</li>
          <li><strong>Legal obligations:</strong> comply with applicable laws, respond to lawful requests from authorities, and enforce our Terms.</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2>4. Third-Party Service Providers</h2>
        <p>
          We share data with the following third-party providers solely to operate the Service. Each provider
          has its own privacy policy and data processing terms.
        </p>
        <ul>
          <li>
            <strong>Amazon (SP-API / PA-API):</strong> When you connect your Amazon seller account, we submit
            API requests to Amazon using your OAuth token. Amazon&apos;s Privacy Notice governs how Amazon
            processes data on its end.
          </li>
          <li>
            <strong>Stripe, Inc.:</strong> Processes all payment card transactions. Stripe receives your email
            address and payment information. See Stripe&apos;s Privacy Policy at stripe.com/privacy.
          </li>
          <li>
            <strong>Resend:</strong> Delivers transactional emails (password reset links, account notices).
            Resend receives your email address for delivery purposes.
          </li>
          <li>
            <strong>Upstash:</strong> Provides serverless Redis used for per-user rate limiting. Upstash may
            process hashed user identifiers and request metadata.
          </li>
          <li>
            <strong>Railway:</strong> Hosts the Service&apos;s application and database infrastructure. Railway
            operates the servers on which your account data is stored.
          </li>
          <li>
            <strong>OpenAI (optional):</strong> If AI-powered features are enabled, product analysis data may
            be submitted to OpenAI&apos;s API to generate insight text. Data submitted to OpenAI is governed by
            OpenAI&apos;s usage and privacy policies. No personally identifiable account information is sent to
            OpenAI.
          </li>
        </ul>
        <p>
          We do not sell, rent, or trade your personal information to any third party for marketing or
          advertising purposes.
        </p>
      </section>

      <section className="space-y-3">
        <h2>5. Data Retention</h2>
        <ul>
          <li>
            <strong>Account data</strong> is retained for as long as your account exists. If you delete your
            account, we will delete or anonymize your personal data within a reasonable period, except where
            retention is required by law (e.g., tax records, fraud prevention).
          </li>
          <li>
            <strong>Usage records</strong> are retained for up to 13 months to support billing disputes and
            quota management.
          </li>
          <li>
            <strong>API response cache</strong> entries expire automatically (typically within 24 hours) and
            are not linked to identifiable individuals.
          </li>
          <li>
            <strong>Logs</strong> are retained for up to 90 days for security and debugging purposes.
          </li>
          <li>
            <strong>Amazon OAuth tokens</strong> are deleted immediately when you disconnect your Amazon account
            from Settings.
          </li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2>6. Security</h2>
        <p>We implement technical and organizational measures appropriate to the sensitivity of your data, including:</p>
        <ul>
          <li>AES-GCM encryption for stored Amazon SP-API OAuth tokens.</li>
          <li>bcrypt hashing (cost factor 12) for all stored passwords.</li>
          <li>HTTPS (TLS) for all data in transit.</li>
          <li>HMAC-signed state parameters to prevent OAuth CSRF attacks.</li>
          <li>Per-user rate limiting to prevent brute-force and abuse.</li>
        </ul>
        <p>
          No security measure is perfect or impenetrable. In the event of a security breach affecting your
          personal data, we will notify affected users as required by applicable law.
        </p>
      </section>

      <section className="space-y-3">
        <h2>7. Your Rights and Choices</h2>
        <p>
          Depending on your jurisdiction, you may have the following rights regarding your personal data.
          Contact us to exercise any of these rights; we will respond within the timeframes required by law.
        </p>
        <ul>
          <li>
            <strong>Access:</strong> request a copy of the personal data we hold about you.
          </li>
          <li>
            <strong>Correction:</strong> update inaccurate or incomplete information (email, name, and profile
            image can be updated directly in Settings).
          </li>
          <li>
            <strong>Deletion:</strong> request deletion of your account and associated personal data, subject
            to legal retention obligations.
          </li>
          <li>
            <strong>Objection / restriction:</strong> object to or request restriction of certain processing
            activities where permitted by law.
          </li>
          <li>
            <strong>Portability:</strong> request your data in a machine-readable format where technically
            feasible and legally required.
          </li>
          <li>
            <strong>Withdraw consent:</strong> where processing is based on consent, you may withdraw it at any
            time without affecting the lawfulness of prior processing.
          </li>
        </ul>
        <p>
          You can disconnect your Amazon account at any time from Settings &rarr; Amazon Account, which
          immediately revokes and deletes the stored OAuth token.
        </p>
      </section>

      <section className="space-y-3">
        <h2>8. Cookies and Local Storage</h2>
        <p>
          The Service uses the following browser storage mechanisms:
        </p>
        <ul>
          <li>
            <strong>Session cookies:</strong> set by NextAuth to maintain your authenticated session. These are
            httpOnly and secure, and expire when you sign out.
          </li>
          <li>
            <strong>Preference cookies:</strong> store your UI theme and appearance preferences across sessions.
            No personal information is stored in these cookies.
          </li>
          <li>
            <strong>localStorage:</strong> used by the browser to store saved product lists and appearance
            preferences. This data stays on your device and is not transmitted to our servers.
          </li>
        </ul>
        <p>We do not use advertising cookies, third-party tracking cookies, or analytics pixels.</p>
      </section>

      <section className="space-y-3">
        <h2>9. Children&apos;s Privacy</h2>
        <p>
          The Service is intended for business use by adults. We do not knowingly collect personal data from
          anyone under the age of 18 (or the applicable age of majority in your jurisdiction). If you believe
          we have inadvertently collected such data, please contact us and we will delete it promptly.
        </p>
      </section>

      <section className="space-y-3">
        <h2>10. International Data Transfers</h2>
        <p>
          The Service is hosted in the United States. If you access the Service from outside the United States,
          your data may be transferred to, stored in, and processed in the United States or other countries
          where our service providers operate. By using the Service, you consent to such transfers.
        </p>
        <p>
          Where required by applicable law (such as the GDPR for users in the European Economic Area), we rely
          on appropriate legal mechanisms, such as Standard Contractual Clauses, to legitimize international
          data transfers.
        </p>
      </section>

      <section className="space-y-3">
        <h2>11. Changes to This Policy</h2>
        <p>
          We may update this Privacy Policy from time to time. When we make material changes, we will post the
          revised Policy with a new &quot;Last updated&quot; date. Where required by law, we will provide
          additional notice. Your continued use of the Service after changes take effect constitutes acceptance
          of the revised Policy.
        </p>
      </section>

      <section className="space-y-3">
        <h2>12. Contact Us</h2>
        <p>
          For privacy inquiries, data subject requests, or questions about this Policy, please contact us
          {contact ? (
            <>
              {" "}at{" "}
              <a href={`mailto:${contact}`} className="font-medium text-teal-700 hover:underline">
                {contact}
              </a>
              .
            </>
          ) : (
            ". (Set SUPPORT_EMAIL or NEXT_PUBLIC_SUPPORT_EMAIL to display a contact address here.)"
          )}
        </p>
        <p>We aim to respond to all privacy-related requests within 30 days.</p>
      </section>
    </LegalDocShell>
  );
}
